# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Alarm Clocks
version: "1.0.0"
slug: alarmclocks
description: Alarm clocks for Home Assistant.
url: "https://github.com/KuraiAndras/home-assistant-alarm-clocks"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
